#
# This file is part of package:
# Sylius Size Chart Plugin
#
# @copyright MADCODERS Team (www.madcoders.co)
# @licence For the full copyright and license information, please view the LICENSE
#
# Architects of this package:
# @author Leonid Moshko <l.moshko@madcoders.pl>
# @author Piotr Lewandowski <p.lewandowski@madcoders.pl>
#

madcoders_sizechart_credits:
    path: /madcoders/sizechart/credits
    defaults:
        _controller: Madcoders\SyliusSizechartPlugin\Controller\CreditsController
