#
# This file is part of package:
# Sylius Size Chart Plugin
#
# @copyright MADCODERS Team (www.madcoders.co)
# @licence For the full copyright and license information, please view the LICENSE
#
# Architects of this package:
# @author Leonid Moshko <l.moshko@madcoders.pl>
# @author Piotr Lewandowski <p.lewandowski@madcoders.pl>
#

imports:
    - { resource: "@MadcodersSyliusSizechartPlugin/Resources/config/grids.yaml" }

knp_gaufrette:
    adapters:
        size_chart:
            local:
                directory: "%sylius_core.public_dir%/media/size_chart"
                create: true
    filesystems:
        size_chart:
            adapter: size_chart

sylius_ui:
    events:
        sylius.shop.product.show.add_to_cart_form:
            blocks:
                before_add_to_cart:
                    template: "@MadcodersSyliusSizechartPlugin/Shop/Sizechart/view.html.twig"
                    priority: 35
