#
# This file is part of package:
# Sylius Size Chart Plugin
#
# @copyright MADCODERS Team (www.madcoders.co)
# @licence For the full copyright and license information, please view the LICENSE
#
# Architects of this package:
# @author Leonid Moshko <l.moshko@madcoders.pl>
# @author Piotr Lewandowski <p.lewandowski@madcoders.pl>
#

imports:
    - { resource: "@MadcodersSyliusSizechartPlugin/Resources/config/grids/madcoders_sizechart_admin_size_chart_grid.yml" }
